services: 
  db:
    image: postgres
    environment:
      TZ: 'America/Fortaleza'
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TERM: xterm-256color
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: bash -c "bash config/setup_app.sh"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      TZ: 'America/Fortaleza'
      TERM: xterm-256color
    env_file:
      - ./.env.dev
    volumes:
      - .:/home/app/web
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  psql-data: