name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Install dependencies
        run: bundle install

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    container: ruby:3.4.2
    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gems
        run: |
          bundle install
          apt update -y
          apt install chromium -y

      - name: Setup Rails DB
        run: bin/rails db:setup
        env:
          DB_HOST: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres

      - name: RSpec
        run: bin/bundle exec rake spec
        env:
          DB_HOST: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          REDIS_URL: redis://redis:6379/1
